// ─────────────────────────────────────────────────────────────
// Prompt Templates
// ─────────────────────────────────────────────────────────────

export const PROMPT_TEMPLATES: Record<string, { name: string; emoji: string; template: string }> = {
    "new_feature": {
        name: "🚀 New Feature",
        emoji: "🚀",
        template: [
            "## New Feature: [Feature Name]",
            "",
            "### What:",
            "[Describe the feature in 1-2 sentences]",
            "",
            "### Why:",
            "[Business justification / user story]",
            "",
            "### Where:",
            "- Files to create: [list new files]",
            "- Files to modify: [list existing files]",
            "",
            "### Acceptance Criteria:",
            "- [ ] [Criterion 1]",
            "- [ ] [Criterion 2]",
            "- [ ] Tests pass",
            "",
            "### Constraints:",
            "- Framework: [specify]",
            "- Must NOT break: [specify]",
        ].join("\n"),
    },
    "refactor": {
        name: "🔧 Refactor",
        emoji: "🔧",
        template: [
            "## Refactor: [Component/Module Name]",
            "",
            "### Current State:",
            "[Describe what exists and why it needs refactoring]",
            "",
            "### Target State:",
            "[Describe the desired architecture/pattern]",
            "",
            "### Files to Refactor:",
            "- `path/to/file.ts` — [what changes]",
            "",
            "### Rules:",
            "- Zero behavior changes (pure refactor)",
            "- All existing tests must pass",
            "- Add types where missing",
        ].join("\n"),
    },
    "bug_fix": {
        name: "🐛 Bug Fix",
        emoji: "🐛",
        template: [
            "## Bug Fix: [Brief Description]",
            "",
            "### Steps to Reproduce:",
            "1. [Step 1]",
            "2. [Step 2]",
            "",
            "### Expected Behavior:",
            "[What should happen]",
            "",
            "### Actual Behavior:",
            "[What actually happens]",
            "",
            "### Error Output:",
            "```",
            "[Paste error/stack trace here]",
            "```",
            "",
            "### Suspected Root Cause:",
            "[Your hypothesis]",
            "",
            "### Fix Scope:",
            "- Only modify: [specific files]",
            "- Do NOT touch: [protected files]",
        ].join("\n"),
    },
    "test_suite": {
        name: "🧪 Test Suite",
        emoji: "🧪",
        template: [
            "## Test Suite: [Module/Feature Name]",
            "",
            "### Target Files:",
            "- `path/to/module.ts`",
            "",
            "### Test Types Required:",
            "- [ ] Unit tests",
            "- [ ] Integration tests",
            "- [ ] Edge cases",
            "",
            "### Scenarios to Cover:",
            "1. Happy path: [describe]",
            "2. Error case: [describe]",
            "3. Edge case: [describe]",
            "",
            "### Framework:",
            "- Test runner: [jest/vitest/mocha]",
            "- Assertions: [built-in/chai]",
            "- Coverage target: [80%+]",
        ].join("\n"),
    },
    "api_endpoint": {
        name: "🌐 API Endpoint",
        emoji: "🌐",
        template: [
            "## API Endpoint: [METHOD] /path/to/endpoint",
            "",
            "### Purpose:",
            "[What this endpoint does]",
            "",
            "### Request:",
            "```json",
            '{ "field": "type" }',
            "```",
            "",
            "### Response (200):",
            "```json",
            '{ "field": "type" }',
            "```",
            "",
            "### Error Responses:",
            "- 400: [when]",
            "- 401: [when]",
            "- 404: [when]",
            "",
            "### Auth Required: [Yes/No]",
            "### Rate Limited: [Yes/No]",
        ].join("\n"),
    },
};
